remote_theme: arca-dpss/ARCA-ghpages
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Prova
description: Repository del corso ARCA Introduzione a R
show_downloads: [true]
