---
title: Introduzione a R
subtitle: Elementi di base ad applicazioni avanzate
author: Filippo Gambarota
output: pdf_document
---

Nel mondo accademico il panorama del software open-source e riproducibile si sta consolidando come la modalità di lavoro più professionale e avanzata. Allo stesso tempo, per poter usare questi strumenti, sono richieste competenze come basi di programmazione e la flessibilità a imparare diversi linguaggi e software. Uno dei più potenti e versatili linguaggi nell’ambito accademico ed anche aziendale è sicuramente R. 

R è un linguaggio di programmazione open-source che vanta una community estremamente attiva e una quantità di estensioni che permettono di analizzare dati, produrre documenti e automatizzare operazioni complesse. 

In questo corso di 20 ore partiremo dalla basi di R come linguaggio acquisendo competenze utili a comprendere la programmazione in generale. Verranno poi presentate le principali caratteristiche specifiche di R come i vari tipi di oggetti, le strutture dati ed anche aspetti più avanzati come la creazione di funzioni in modo da poter utilizzare poi il linguaggio in autonomia. Saranno poi accennati gli aspetti di programmazione in R che una volta acquisiti potranno essere facilmente trasferibili ad altri linguaggi e software.
Tutti i vari argomenti saranno accompagnati da esercizi pratici, materiale per l’approfondimento e suggerimenti su come organizzare e ottimizzare al meglio l’utilizzo del software. 

Il materiale e l’organizzazione del corso è disponibile nella repository Github [filippogambarota/corsoR](https://github.com/filippogambarota/corsoR). Inoltre il principale materiale di riferimento per il corso è il libro anch’esso disponibile online su Github [Introduction2R](https://psicostat.github.io/Introduction2R/https://psicostat.github.io/Introduction2R/).