---
title: "Le funzioni TOP in R"
output: 
    bookdown::html_document2:
        toc: true
        toc_float: true
        code_download: true
css: ["../files/css/course_html.css"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Funzioni

In questo documento vediamo alcune funzioni **personalizzate** che possono essere utili durante il corso. Per poterle utilizzare potete copiare e incollare direttamente la funzione per poi salvarla come oggetto.

## `put_random_na()`

```{r}
put_random_na <- function(data, n){
    
    pos <- list(rows = 1:nrow(data),
                cols = 1:ncol(data))
    
    pos <- expand.grid(pos)
    
    na_pos <- sample(1:nrow(pos), n)
    
    for (i in 1:length(na_pos)) {
        
        na_pos_i <- pos[na_pos[i], ]
        
        data[na_pos_i[[1]], na_pos_i[[2]]] <- NA
        
    }
    
    return(data)
    
}
```

Utilizzo:

```{r}
put_random_na(mtcars, 30)
```

## `randomize_case()`

```{r}
randomize_case <- function(x, nletters = 15, n_prob = 0.30){
    new_x <- tolower(x)
    to_randomize <- sample(LETTERS, nletters)
    names(to_randomize) <- tolower(to_randomize)
    n_to_randomize <- floor(length(x) * n_prob)
    id_to_randomize <- sample(1:length(x), n_to_randomize)
    new_x[id_to_randomize] <- stringr::str_replace_all(new_x[id_to_randomize], to_randomize)

    return(new_x)
}
```

Utilizzo:

```{r}
randomize_case(iris$Species)
```




